# Generated by Django 2.2.9 on 2020-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blogpageauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='private_field',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
